version: '3.3'
services:
  web:
    build:
      context: app
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=binotify
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
