version: '3.3'
services:
  web:
    build:
      context: .
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=binotify
    ports:
      - 6543:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
volumes:
  db-data: 
